### Create Category
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Frontend"
}


### Get All Categories
GET http://localhost:3000/categories


### Update Category (adding Subcaategories)
PATCH http://localhost:3000/categories/7
Content-Type: application/json

{
    "parentCategoryId": 5
}